name: Create Archive
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'hello-world.craftx'
        exclusions: '*.git* README.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "hello-world.craftx"
        token: ${{ secrets.GITHUB_TOKEN }}
